language: objective-c
osx_image: xcode7
before_install:
    - mkdir -p ~/Library/RubyMotion
    - (ruby --version)
    - sudo chown -R travis ~/Library/RubyMotion
    - mkdir -p ~/Library/RubyMotion/build
    - sudo motion update
gemfile:
  - Gemfile
script:
    - bundle install
    - bundle exec rake pod:install > /dev/null
    - bundle exec rake clean
    - bundle exec rake spec
